language: go

os:
  - linux
  - osx

go:
  - 1.8

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=frameof.cov github.com/cstockton/pkg/frameof
  - go test -coverprofile=ctxkey.cov github.com/cstockton/pkg/ctxkey

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "*.cov"
